language: ruby
rvm:
  - 2.2.3
cache: bundler
services:
  - postgresql
gemfile: beryx_app/Gemfile
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp beryx_app/config/database.yml.travis beryx_app/config/database.yml
script: 
  - cd beryx_app
  - RAILS_ENV=test bundle exec rake db:reset
  - bundle exec rake spec
