source 'https://rubygems.org'


gem 'rails', '5.0.0.1'
gem 'puma'
gem 'pg'
gem 'bcrypt'
gem 'parallel'
gem 'ransack'
gem 'kaminari'
gem 'sidekiq'
gem 'sidekiq-unique-jobs'
gem 'whenever', require: false
gem 'bootstrap-sass'
gem 'sass-rails'
gem "autoprefixer-rails"
gem 'uglifier'
gem 'coffee-rails'

gem 'jquery-rails'
gem 'jbuilder'
gem 'sdoc', group: :doc
gem 'react-rails'


group :development, :test do
  gem 'rspec-rails'
  gem "factory_girl_rails"
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'capybara'
  gem 'spring'
  gem 'database_cleaner'
  gem 'fuubar'
end

group :development do
  gem 'web-console'
  gem 'spring-commands-rspec'
  gem 'annotate'
  gem 'stackprof'

  # for sidekiq
  gem 'sinatra', :require => nil, github: 'sinatra/sinatra'
end

group :test do
  gem 'rspec-sidekiq'
end

group :production do
end
