source 'https://rubygems.org'


gem 'rails', '4.2.5'
gem 'puma'
gem 'pg'
gem 'bcrypt'
gem 'parallel'
gem 'ransack', '~> 1.7.0'
gem 'kaminari'
gem 'kaminari-bootstrap', '~> 3.0.1'
gem 'sidekiq', '~> 4.0.1'
gem 'sidekiq-unique-jobs', '~> 4.0.13'
gem 'whenever', require: false
gem 'bootstrap-sass', '~> 3.3.6'
gem 'sass-rails', '~> 5.0'
gem "autoprefixer-rails"
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'react-rails', '~> 1.5.0'


group :development, :test do
  gem 'rspec-rails', "~> 3.4.0"
  gem "factory_girl_rails" , "~> 4.5.0"
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'capybara', "~> 2.5.0"
  gem 'spring'
  gem 'database_cleaner'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring-commands-rspec'
  gem 'annotate'
  gem 'stackprof'

  # for sidekiq
  gem 'sinatra', :require => nil
end

group :test do
  gem 'rspec-sidekiq'
end

group :production do
end
