flexbox: no-2009
browsers:
  - "last 2 Firefox versions"
  - "last 2 Chrome versions"
  - "last 1 Safari versions"
  - "last 1 iOS versions"
  - "last 1 ChromeAndroid versions"
  - "last 2 Edge versions"
  - "IE > 10"