---
# vim:ft=ansible
- name: replace apt repository to jp
  become: true
  replace:
    dest=/etc/apt/sources.list
    regexp='//archive\.ubuntu\.com/'
    replace='//jp.archive.ubuntu.com/'
- name: Apt dist-upgrade
  apt: upgrade=dist update_cache=yes
  become: true
- name: Install basic packages
  apt: name={{ item }} state=latest update_cache=yes
  become: true
  with_items:
    - build-essential
    - zsh
    - git
    - tmux
    - vim-nox
    - htop
    - checkinstall
    - wget
- name: Install language-pack-ja
  apt: name=language-pack-ja
  become: true
- name: Generate locale ja_JP.UTF-8
  locale_gen: name=ja_JP.UTF-8
- name: Set default locale
  become: true
  lineinfile: dest=/etc/default/locale
    regexp="LANG"
    line="LANG=ja_JP.utf8"
- shell: "cat /etc/timezone"
  register: current_timezone
  changed_when: false
- name: Set TZ to Asia/Tokyo
  become: true
  command: "timedatectl set-timezone Asia/Tokyo"
  when: 'current_timezone.stdout.find("Asia/Tokyo") == -1'
